# Generated by Django 2.2.1 on 2019-06-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='files'),
        ),
    ]
