# Generated by Django 2.2.2 on 2019-06-24 10:20

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_auto_20190610_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(upload_to=attachments.models.item_directory_path),
        ),
    ]
